### ISSUE TITLE
Can you provide the dist build?

### ISSUE THREAD

**Issue by Mulli** [m-muhsin/celestial#1]
I have installed the theme on a real live testing website.
First issue: rename local host path to the new one.
Solution: **temporary** modify the .js in the dist directory.
Since I did not know how to generate the dist... :-(

Can you provide the dist build?

**Comment by m-muhsin** [comment]
The app.js file is available in the dist folder (ideally it should have been git ignored though).
However, after cloning you can do 'npm install' and 'npm run build' to generate the dist.

**Comment by Mulli** [comment]
Thanks!
