### ISSUE TITLE
Changes in page.jsx not effected in front end 

### ISSUE THREAD

**Issue by pratiweb** [m-muhsin/celestial#10]
Hello 
Your theme very helpful for me like beginner in react , but i want to show more content for pages except title and content , like custom meta fields. I have check ACf fields return in response . But when i try to change in page.jsx by adding some dummy text or field its not effecting front side..
Is there any compile or command need to run ?

**Comment by m-muhsin** [comment]
Hi there,
Thanks for creating the issue. Yes, you have to install the dependencies first using `npm install`.
After that you have to start watching the for file changes using `npm run watch`. Then, whatever change you make will be reflected!

Also, check out the project README.

Thanks!
