### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lesenyeho** [m-muhsin/celestial#2]
<img width="412" alt="screen shot 2018-04-16 at 16 55 17" src="https://user-images.githubusercontent.com/23079090/38816776-26139f1e-4197-11e8-8307-692586885dae.png">

I would like to know why is complaining about this line

**Comment by m-muhsin** [comment]
Could you check your .babelrc configurations please?
Does it say the following:
{
    "presets": [
        "es2015", 
        "react"
    ]
}
?
