### ISSUE TITLE
Pages 404

### ISSUE THREAD

**Issue by justin-bond** [m-muhsin/celestial#3]
Getting a 404 when trying to load a page 

`/wp-json/wp/v2//pages?slug=sample-page 404 (Not Found)`

Looks like its because the object `CelestialSettings.URL.api` already has a trailing slash and when you are adding `"/pages?slug=" + slug` to it, it is doubling up the forward slash. Found this in the files `app.js` and `page.jsx`.

**Comment by m-muhsin** [comment]
Thanks for pointing it out. You are right!

I have fixed and updated the code.
