### ISSUE TITLE
error when run buld on command prompt

### ISSUE THREAD

**Issue by rajkumargaur91** [m-muhsin/celestial#4]
C:\xampp\htdocs\celestial\wp-content\themes\celestial>npm run build

> celestial@1.0.0 build C:\xampp\htdocs\celestial\wp-content\themes\celestial
> webpack

Hash: 0f92de707985886c7ab1
Version: webpack 3.12.0
Time: 543ms
 Asset     Size  Chunks             Chunk Names
app.js  3.46 kB       0  [emitted]  app
   [0] ./src/index.jsx 986 bytes {0} [built] [failed] [1 error]

ERROR in ./src/index.jsx
Module build failed: SyntaxError: C:/xampp/htdocs/celestial/wp-content/themes/celestial/src/index.jsx: Unexpected token (20:4)

  18 |
  19 | const App = () => (
> 20 |     <div id="page-inner">
     |     ^
  21 |         <Header />
  22 |         <div id="content">
  23 |             <Switch>

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! celestial@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the celestial@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rajkumar.gour\AppData\Roaming\npm-cache\_logs\2018-08-16T11_31_41_715Z-debug.log

C:\xampp\htdocs\celestial\wp-content\themes\celestial>

**Comment by m-muhsin** [comment]
Make sure you have .babelrc inside your theme folder with the following content:

{
    "presets": [
        "env", 
        "react"
    ]
}

Thank you!
