### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by newfylox** [m-muhsin/celestial#5]
Hi! Great project you did by the way! I have small questions for you.

* Is there a way to make permalink dynamic? Like updating it on the server side without worrying to set it to `/posts/%postname%/`? If not, where in the code can I change it myself to make it fit with my Wordpress permalink?
* Do you plan to add some widget sections?

Thanks

**Comment by m-muhsin** [comment]
Hi! 

- If you want to try it you can take a look at the React Router Config in index.jsx. For instance you can expose the permalink via wp_localize_script and create dynamic routing.
- I don't have plans for widgets any time soon

Thank you for contacting me. Happy coding!
