### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by jomuji** [m-muhsin/celestial#6]
is there a simple way to get pages working?  having trouble with router

**Comment by m-muhsin** [comment]
Pages are already working using quite simple code. What trouble are you having with router?

**Comment by jomuji** [comment]
hello, i ended up changing route as:

<Route exact path={CelestialSettings.path + ':slug'} component={props => <Page {...props} />} />

and everything is working fine now, i hope if somebody has problems with pages could use this quickfix.

ps: great tutorial! thanks

regards.

**Comment by m-muhsin** [comment]
Awesome! Glad that you were able to solve it. Thank you 💯
