### ISSUE TITLE
jQuery can't be removed

### ISSUE THREAD

**Issue by devbyray** [m-muhsin/celestial#7]
Thanks for creating this great repo and writing everything on Smashing magazine!

I only noticed that jQuery can't be removed because it is a dependency of **ScrollMagic**. In the readme, you wrote that you removed jQuery, but it is still loading. I thought you wanted to know ;-)

**Comment by m-muhsin** [comment]
You were right. ScrollMagic has been using the jQuery that comes with WordPress after I commented out the enqueued jQuery version. I have updated the Readme now 👍 
Thanks @raymonschouwenaar
